trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionPath: "DotNetCore.DI.Interception/DotNetCore.DI.Interception.sln"

steps:
- script: dotnet build $(solutionPath) --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test $(solutionPath) --configuration $(buildConfiguration) --collect "Code coverage"
  displayName: 'dotnet test $(buildConfiguration)'